music/discogs/urls.py
from django.urls import path

from . import views

app_name = 'discogs'
urlpatterns = [
    # ex: /discogs/
    path('', views.index, name='index'),
    # ex: /discogs/search
    path('search/', views.index_search, name='index_search'),
    #path('search/<int:artist_id>', views.index_search, name='index_search'),
    # ex: /discogs/artist/
    path('artist/', views.artist_list, name='artist_list'),
    # ex: /discogs/artist/search/regexp/
    path('artist/search/<str:artist_regexp>/', views.artist_for_regexp, name='artist_for_regexp'),
    # ex: /discogs/artist/5/
    path('artist/<int:artist_id>/', views.artist_info, name='artist_info'),
    # ex: /discogs/artist/list/5/
    path('artist/list/<int:artist_id>/', views.items_for_artist, name='items_for_artist'),
    # ex: /discogs/label/
    path('label/', views.label_list, name='label_list'),
    # ex: /discogs/label/search/regexp/
    path('label/search/<str:label_regexp>/', views.label_for_regexp, name='label_for_regexp'),
    # ex: /discogs/label/5/
    path('label/<int:label_id>/', views.label_info, name='label_info'),
    # ex: /discogs/label/list/5/
    path('label/list/<int:label_id>/', views.items_for_label, name='items_for_label'),
    # ex: /discogs/format/
    path('format/', views.format_list, name='format_list'),
    # ex: /discogs/format/5/
    path('format/<int:format_id>/', views.format_info, name='format_info'),
    # ex: /discogs/format/list/5/
    path('format/list/<int:format_id>/', views.items_for_format, name='items_for_format'),
    # ex: /discogs/5/
    path('<int:release_id>/', views.item_details, name='item_details'),
]

music/music/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('discogs/', include('discogs.urls', namespace="discogs")),
    path('admin/', admin.site.urls),
]

music/discogs/models.py
from django.db import models

# Create your models here.

from django.db import models

class Artist(models.Model):
    artist = models.CharField(max_length=200)
    def __str__(self):
        return self.artist

class Format(models.Model):
    format = models.CharField(max_length=200)
    def __str__(self):
        return self.format

class Label(models.Model):
    label = models.CharField(max_length=200)
    def __str__(self):
        return self.label

class Item(models.Model):
    catalogue_number = models.CharField(max_length=200)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    label = models.ForeignKey(Label, on_delete=models.CASCADE)
    format = models.ForeignKey(Format, on_delete=models.CASCADE)
    released = models.CharField(max_length=6)
    release_id = models.IntegerField(default=0)
    def __str__(self):
        item_tuple = (self.catalogue_number, self.label.label, self.artist.artist, self.title, self.format.format, self.released)
        return "<tr><td>" + "</td><td>".join(item_tuple) + "</td></tr>"

music/discogs/forms.py
from django import forms
from django.shortcuts import get_object_or_404, get_list_or_404
from .models import Artist, Label, Format, Item

# Create your forms here.

class SearchForm(forms.Form):
    artist_choice = forms.ModelChoiceField(queryset = Artist.objects.all(), required=False)
    label_choice = forms.ModelChoiceField(queryset = Label.objects.all(), required=False)
    format_choice = forms.ModelChoiceField(queryset = Format.objects.all(), required=False)
#    text_choice = forms.CharField(required=False)

music/discogs/views.py
from django.shortcuts import get_object_or_404, get_list_or_404, render, HttpResponse, HttpResponseRedirect
from django.template import loader, Context, Template

#from admin.models import Choice
from .models import Artist, Label, Format, Item

from .forms import SearchForm

#    catalogue_number = models.CharField(max_length=200)
#    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
#    title = models.CharField(max_length=200)
#    label = models.ForeignKey(Label, on_delete=models.CASCADE)
#    format = models.ForeignKey(Format, on_delete=models.CASCADE)
#    released = models.DateTimeField('date released')
#    release_id = models.IntegerField(default=0)

import re

def index(request):
    form = SearchForm()
    context = {'form' : form}
    return render(request, 'discogs/index.html', context)

def collate_item_list(item_list):
    output_list = []
    for item in item_list:
      output_list.append({'catalogue_number' : item.catalogue_number, 'artist' : item.artist, 'label' : item.label, 'title' : item.title, 'format' : item.format, 'released' : item.released, 'release_id' : item.release_id})
    return output_list

def index_search(request):
    artist_id = request.POST['artist_choice']
    label_id = request.POST['label_choice']
    format_id = request.POST['format_choice']
#    text = request.POST['text_choice']

    item_list = Item.objects.order_by('artist', 'released')

    if artist_id:
      item_list = item_list.filter(artist=artist_id)

    if label_id:
      item_list = item_list.filter(label=label_id)

    if format_id:
      item_list = get_list_or_404(item_list, format=format_id)
    else:
      item_list = get_list_or_404(item_list)

    output_list = collate_item_list(item_list)
    return render(request, 'discogs/search_results.html', {'output_list' : output_list})

def type_list(request, object, file, hash_name):
    type_list = get_list_or_404(object)
    type_hash_list=[]
    for type in type_list:
      stype = str(type)
      ptype=re.sub("\s+", "+", stype)
      ptype1=re.sub("/", "%2F", ptype)
      type_hash={'name' : stype, 'regexp' : ptype1, 'id' : type.id}
      type_hash_list.append(type_hash)
    return render(request, 'discogs/' + file + '.html', {hash_name : type_hash_list})

def artist_for_regexp(request, artist_regexp):
    response = "https://www.discogs.com/search/?type=artist&title=%s"
    return HttpResponseRedirect(response % artist_regexp)

def artist_info(request, artist_id):
    artist_list = get_list_or_404(Item, artist=artist_id)
    item_list = []
    for artist in artist_list:
      item_list.append({'catalogue_number' : artist.catalogue_number, 'label' : artist.label, 'title' : artist.title, 'format' : artist.format, 'released' : artist.released, 'release_id' : artist.release_id})
    artist = get_object_or_404(Artist, pk=artist_id)
    sartist = str(artist)
    partist=re.sub("\s+", "+", sartist)
    partist1=re.sub("/", "%2F", partist)
    artist_hash={'name' : sartist, 'regexp' : partist1, 'item_list' : item_list}
    return render(request, 'discogs/artist_info.html', artist_hash)

def artist_list(request):
    return type_list(request, Artist, "artist_list", "artist_hash_list")

def items_for_artist(request, artist_id):
    item_list = get_list_or_404(Item, artist=artist_id)
    output_list = collate_item_list(item_list)
    return render(request, 'discogs/search_results.html', {'output_list' : output_list})

def label_for_regexp(request, label_regexp):
    response = "https://www.discogs.com/search/?type=label&title=%s"
    return HttpResponseRedirect(response % label_regexp)

def label_info(request, label_id):
    label_list = get_list_or_404(Item, label=label_id)
    item_list = []
    for label in label_list:
      item_list.append({'catalogue_number' : label.catalogue_number, 'artist' : label.artist, 'title' : label.title, 'format' : label.format, 'released' : label.released, 'release_id' : label.release_id})
    label = get_object_or_404(Label, pk=label_id)
    slabel = str(label)
    plabel=re.sub("\s+", "+", slabel)
    plabel1=re.sub("/", "%2F", plabel)
    label_hash={'name' : slabel, 'regexp' : plabel1, 'item_list' : item_list}
    return render(request, 'discogs/label_info.html', label_hash)

def label_list(request):
    return type_list(request, Label, "label_list", "label_hash_list")

def items_for_label(request, label_id):
    item_list = get_list_or_404(Item, label=label_id)
    output_list = collate_item_list(item_list)
    return render(request, 'discogs/search_results.html', {'output_list' : output_list})

def format_info(request, format_id):
    format = get_object_or_404(Format, pk=format_id)
    return render(request, 'discogs/format_info.html', {'format': format})

def format_list(request):
    format_list = get_list_or_404(Format)
    return render(request, 'discogs/format_list.html', {'format_list': format_list})

def items_for_format(request, format_id):
    item_list = get_list_or_404(Item, label=label_id)
    output_list = collate_item_list(item_list)
    return render(request, 'discogs/search_results.html', {'output_list' : output_list})

def item_details(request, release_id):
    response = "https://www.discogs.com/release/%s"
    return HttpResponseRedirect(response % release_id)

music/discogs/templates/discogs/artist_info.html
<h1>Artist : {{ name }}</h1>
<table border="1">
<tr><th>Catalogue Number</th><th>Label</th><th>Title</th><th>Format</th><th>Released</th><th>Discogs Page</th></tr>
{% for item in item_list %}
  <tr><td>{{ item.catalogue_number }}</td><td>{{ item.label }}</td><td>{{ item.title }}</td><td>{{ item.format }}</td><td>{{ item.released }}</td><td><a href="{% url 'discogs:item_details' item.release_id %}">Discogs entry for {{ item.release_id }}</td></tr> 
{% endfor %}
</table>

<p><a href="{% url 'discogs:artist_for_regexp' regexp %}">Discogs entry for {{ name }}</a></p>

music/discogs/templates/discogs/artist_list.html
<h1>Artists</h1>
<table border="1">
<tr><th>Items</th><th>Discogs Page</th></tr>
{% for artist in artist_hash_list %}
    <tr><td><a href="{% url 'discogs:artist_info' artist.id %}">{{ artist.name}}</a></td><td><a href="{% url 'discogs:artist_for_regexp' artist.regexp %}">{{ artist.name }}</a></td></tr>
{% endfor %}
</table>

music/discogs/templates/discogs/format_info.html
{{ format }}

music/discogs/templates/discogs/format_list.html
<h1>Formats</h1>
<ul>
{% for format in format_list %}
    <li>{{ format }}</li>
{% endfor %}
</ul>

music/discogs/templates/discogs/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'discogs/style.css' %}">

<center>
<form action="{% url 'discogs:index_search' %}" method="post">
{% csrf_token %}
<table border="1">
{{ form }}
</table>
<input type="submit" value="Search">
</form>
</center>

<hr>
<p>The above search boxes return fewer items, the more search terms are added.</p>
<p>If you want to list all of the <a href="{% url 'discogs:artist_list' %}">artists</a> you will see a two column display.</p>
<p>The first column will show all of the items for that artist and the second column links to the discogs entry for that artist name.</p>
<p>The <a href="{% url 'discogs:label_list' %}">labels</a> are similarly displayed.</p>
<p>Each of the <a href="{% url 'discogs:format_list' %}">formats</a> returned from the CSV file is listed. I think that I may well
massage this data further, though I am presently considering the best approach.</p>
<hr>

music/discogs/templates/discogs/label_info.html
<h1>Label : {{ name }}</h1>
<table border="1">
<tr><th>Catalogue Number</th><th>Artist</th><th>Title</th><th>Format</th><th>Released</th><th>Discogs Page</th></tr>
{% for item in item_list %}
  <tr><td>{{ item.catalogue_number }}</td><td>{{ item.artist }}</td><td>{{ item.title }}</td><td>{{ item.format }}</td><td>{{ item.released }}</td><td><a href="{% url 'discogs:item_details' item.release_id %}">Discogs entry for {{ item.release_id }}</td></tr> 
{% endfor %}
</table>

<p><a href="{% url 'discogs:label_for_regexp' regexp %}">Discogs entry for {{ name }}</a></p>

music/discogs/templates/discogs/label_list.html
<h1>Labels</h1>
<table border="1">
<tr><th>Items</th><th>Discogs Page</th></tr>
{% for label in label_hash_list %}
    <tr><td><a href="{% url 'discogs:label_info' label.id %}">{{ label.name}}</a></td><td><a href="{% url 'discogs:label_for_regexp' label.regexp %}">{{ label.name }}</a></td></tr>
{% endfor %}
</table>

music/discogs/templates/discogs/search_results.html
<table border="1">
<!-- <tr><th>Catalogue Number</th><th>Artist</th><th>Label</th><th>Title</th><th>Format</th><th>Released</th><th>Discogs Page</th></tr> -->
<tr>
<th>Artist</th>
<th>Title</th>
<th>Catalogue Number</th>
<th>Label</th>
<th>Format</th>
<th>Released</th>
<th>Discogs Page</th>
</tr>
{% for item in output_list %}
  <tr>
    <td>{{ item.artist }}</td>
    <td>{{ item.title }}</td>
    <td>{{ item.catalogue_number }}</td>
    <td>{{ item.label }}</td>
    <td>{{ item.format }}</td>
    <td>{{ item.released }}</td>
    <td><a href="{% url 'discogs:item_details' item.release_id %}">Discogs entry for {{ item.release_id }}</td>
  </tr> 
<!--  <tr><td>{{ item.catalogue_number }}</td><td>{{ item.artist }}</td><td>{{ item.label }}</td><td>{{ item.title }}</td><td>{{ item.format }}</td><td>{{ item.released }}</td><td><a href="{% url 'discogs:item_details' item.release_id %}">Discogs entry for {{ item.release_id }}</td></tr> -->
{% endfor %}
</table>